# Generated by Django 4.2.5 on 2023-10-10 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductosLocales', '0003_local_ubicacion_producto_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='descripcion',
            field=models.TextField(default=''),
        ),
    ]
