# Generated by Django 4.2.5 on 2023-10-26 17:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ProductosLocales', '0007_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
