# Generated by Django 4.2.5 on 2023-11-07 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductosLocales', '0008_review_fecha_creacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='productos', to='ProductosLocales.tag'),
        ),
    ]
