# Generated by Django 4.2.5 on 2023-11-07 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductosLocales', '0009_tag_producto_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
